# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oNJHr1JulIifqy-HuMNIYFB0rcaw_8GL
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Departements/departement.xlsx")
data.head()

x = data.drop(['Disease', 'Unnamed: 0'], axis = 1)
y = data.Disease

from sklearn.model_selection import train_test_split

x_train, x_test, y_train , y_test = train_test_split(x ,y, random_state = 50)

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = RandomForestClassifier(n_estimators=200)
model.fit(x_train, y_train)
predictions = model.predict(x_test)
accuracy_score(y_test, predictions)

model = LogisticRegression(max_iter = 1000)
model.fit(x_train, y_train)
predictions = model.predict(x_test)
accuracy_score(y_test, predictions)

import pickle
pickle.dump(model, open('Departements.pkl', 'wb'))